name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  env:
    name: Build & Publish debian source package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: publish
        name: Build and push a debian source package to launchpad
        env:
          PPA_GPG_PRIVATE_KEY: ${{secrets.PPA_GPG_PRIVATE_KEY}}
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's#^refs/tags/v([0-9\.]+)(-.*)?#\1#')
          sudo ./setup-build-env.sh
          ./build.sh "${VERSION}"